version: '3.8'

services:
  web:
    build: .
    container_name: ranchdubonheur
    environment:
      - DEFAULT_USERNAME=${DEFAULT_USERNAME}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
      - SA_PASSWORD=${SA_PASSWORD}
    depends_on:
      - ranch_db
    networks:
      - nginx-proxy-network
    ports:
      - "43210:80"
    entrypoint: ["dotnet", "RanchDuBonheur.dll", "--ConnectionStrings:DefaultConnection", "Server=ranch_db;Database=RanchDuBonheurDb;User Id=SA;Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True"]

  ranch_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:

networks:
  nginx-proxy-network:
    external:
      name: nginx-proxy-network

