version: '3.8'

services:
  webapp:
    image: ranchdubonheur
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:92"
    networks:
      - ranch-net
      - nginx-proxy-network
    environment:
      - ConnectionStrings__DefaultConnection=Server=database.ranchdubonheur.fr;Database=RanchDuBonheurDB;User=sa;Password=${SA_PASSWORD};Encrypt=True;TrustServerCertificate=True;
      - DefaultUser__Username=${DEFAULT_USERNAME}
      - DefaultUser__Email=${DEFAULT_EMAIL}
      - DefaultUser__Password=${DEFAULT_PASSWORD}
    depends_on:
      - db

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - ranch-net
      - nginx-proxy-network

networks:
  ranch-net:
    driver: bridge
    name: ranch-net
  nginx-proxy-network:
    external: true