version: '3.8'

services:
  web:
    build: .
    container_name: ranchdubonheur
    environment:
      - ASPNETCORE_ENVIRONMENT=Production 
      - ConnectionStrings__DefaultConnection=Server=ranch_db;Database=RanchDuBonheurDb;User Id=SA;Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True
      - DEFAULT_USERNAME=${DEFAULT_USERNAME}
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - DEFAULT_PASSWORD=${DEFAULT_PASSWORD}
    depends_on:
      - ranch_db
    networks:
      - ranchdubonheur_default 
    ports:
      - "80:80"
    
  ranch_db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
    volumes:
      - sql_data:/var/opt/mssql
    networks:
      - ranchdubonheur_default

volumes:
  sql_data:

networks:
  ranchdubonheur_default:
    driver: bridge 
