version: '3.8'

services:
  webapp:
    image: ranchdubonheur
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=RanchDuBonheurDB;User=sa;Password=${SA_PASSWORD}
      - DefaultUser__Username=${DEFAULT_USERNAME}
      - DefaultUser__Email=${DEFAULT_EMAIL}
      - DefaultUser__Password=${DEFAULT_PASSWORD}

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
